### PR TITLE
Remove unnecessary CSS files

### PR DESCRIPTION
**Pull request by SheepTester**
Initially for some reason we wanted our CSS to be separate. The template ones aren't and everything works fine

### CODE REVIEW

**Comment by heaucques** [comment]
I is agree

**Comment by SheepTester** [comment]
You click the merge button

**Comment by heaucques** [comment]
Why click merge button

**Comment by heaucques** [comment]
i thought you said to keep everything open?

**Comment by SheepTester** [comment]
No, I said to keep everything unlocked

**Pull request merged**
